Add generic font interface + sample (#192)
tophat2d/tophat pull request #200
Opened 2024-07-14 20:15 UTC by marekmaskarinec

2024-07-14 20:19 UTC, vtereshkov commented
@marekmaskarinec Is `canvas::drawText()` removed?

2024-07-14 20:26 UTC, marekmaskarinec commented
No, the old api stays for those who want to use it. But now there is also the `canvas::pixelFont` built over it.

2024-07-14 20:35 UTC, skejeton commented on umka/canvas.um
> +type __PixelFont = struct { }
Do we need the double underscore?

2024-07-14 20:37 UTC, skejeton commented on umka/font.um
> +type TtfFont* = struct { _: ^struct{} }
I think it's OK to export it. This is just a minor nitpick - I think `TtfFont` doesn't look very nice, maybe we can call it `Truetype`.

2024-07-14 20:39 UTC, skejeton commented on umka/font.um
> +// `font.load`, or a built in canvas can be used from `canvas.pixelFont`.
Should be `font::load` and `canvas::pixelFont`

2024-07-14 20:41 UTC, skejeton requested changes
Looks good! Only minor nitpicks like in documentation and naming. I'm going to test it on SaveScum.

2024-07-14 20:44 UTC, skejeton commented on umka/canvas.um
> +	"font.um"
This import isn't used here.

2024-07-14 20:47 UTC, skejeton commented
Works with no issues.

2024-07-16 10:45 UTC, marekmaskarinec commented
@skejeton I have incorporated your suggestions. Are we ok to merge now?

2024-07-16 13:00 UTC, merged